#! /bin/bash
# This software is a part of the A.O.D apprepo project
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
set -e
# APPDIR=`pwd`

PATH=${APPDIR}/perl/bin:${PATH}
PATH=${APPDIR}/application/bin:${PATH}
export PATH=${PATH}


XDG_DATA_DIRS=${APPDIR}/application/share:${XDG_DATA_DIRS}
XDG_DATA_DIRS=${APPDIR}/perl/share:${XDG_DATA_DIRS}
export XDG_DATA_DIRS=${XDG_DATA_DIRS}


LD_LIBRARY_PATH=${APPDIR}/perl/lib:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}

export PERL5LIB=${APPDIR}/perl/lib/perl5:${PERL5LIB}
export PERL5LIB=${APPDIR}/perl/lib/perl5/vendor_perl:${PERL5LIB}
export PERL5LIB=${APPDIR}/perl/share/perl5:${PERL5LIB}
export PERL5LIB=${APPDIR}/perl/share/perl5/vendor_perl:${PERL5LIB}
export PERL5LIB=${PERL5LIB}

cd ${OWD}

${APPDIR}/perl/bin/perl ${APPDIR}/application/bin/shutter $@